version: 2
updates:
  - package-ecosystem: nuget
    assignees:
      - "jcdcdev"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"
    commit-message:
      prefix: "chore"
      include: "scope"
    target-branch: "dev"

  - package-ecosystem: npm
    assignees:
      - "jcdcdev"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"
    commit-message:
      prefix: "chore"
      include: "scope"
    target-branch: "dev"
