// This file is auto-generated by @hey-api/openapi-ts

export { client, type CreateClientConfig } from './client.gen';
export { type Options, SimpleDashboards } from './sdk.gen';
export type { ClientOptions, GetRenderByDashboardData, GetRenderByDashboardErrors, GetRenderByDashboardResponse, GetRenderByDashboardResponses, SimpleDashboardRenderModel } from './types.gen';
