// This file is auto-generated by @hey-api/openapi-ts

export type SimpleDashboardRenderModel = {
    body: string;
};

export type GetUmbracoSimpledashboardsApiV1RenderByDashboardData = {
    dashboard: string;
};

export type GetUmbracoSimpledashboardsApiV1RenderByDashboardResponse = ((SimpleDashboardRenderModel));